Update data-loader to utilize Key properties in the model
CBIIT/icdc-dataloader pull request #99
Opened 2024-09-09 15:18 UTC by wfy1997

2024-09-13 20:59 UTC, n2iw requested changes
When using ICDC model, I got following errors:
`Traceback (most recent call last):
  File "/Users/yingm3/work/code/icdc/data-loader/./loader.py", line 318, in <module>
    main(parse_arguments())
  File "/Users/yingm3/work/code/icdc/data-loader/./loader.py", line 230, in main
    schema = ICDC_Schema(config.schema_files, props)
  File "/Users/yingm3/work/code/icdc/data-loader/icdc_schema.py", line 99, in __init__
    node_id_list = self.get_node_id(node_type)
  File "/Users/yingm3/work/code/icdc/data-loader/icdc_schema.py", line 111, in get_node_id
    for prop in self.org_schema[NODES][node_type][PROPERTIES]:
TypeError: 'NoneType' object is not iterable`

2024-09-17 15:00 UTC, n2iw requested changes

2024-09-17 15:46 UTC, wfy1997 commented on icdc_schema.py
> +            if KEY in self.org_schema[PROP_DEFINITIONS][prop]:
It will handle the Key: false situation
with code "if self.org_schema[PROP_DEFINITIONS][prop][KEY]:"

2024-09-23 20:32 UTC, n2iw requested changes
It seems when creating indexes, the Key properties read from model file are not included. You can test this by creating a new database, then remove some ID fields from prop file, then observe the output related to index creation.

2024-10-07 23:25 UTC, n2iw approved these changes
LGTM

2024-10-07 23:25 UTC, merged